# Generated by Django 6.0.4 on 2026-05-01 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nida', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField()),
                ('birth_cert_number', models.CharField(max_length=50, unique=True)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('parent_occupation', models.CharField(max_length=100)),
                ('parent_nida', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classlevel')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district')),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
        ),
        migrations.CreateModel(
            name='OtherRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.relationship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_relatives', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
