# Generated by Django 6.0.4 on 2026-05-02 13:24

from django.db import migrations, models
from django.utils import timezone


def backfill_registration_numbers(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    year = timezone.now().strftime('%Y')
    count = 0
    for student in Student.objects.filter(registration_number__isnull=True):
        count += 1
        student.registration_number = f'BIA-{year}-{count:04d}'
        student.save(update_fields=['registration_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registration_date']},
        ),
        migrations.AlterModelOptions(
            name='studentclasshistory',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Student class histories'},
        ),
        # Step 1: Add field as nullable first
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        # Step 2: Backfill existing records
        migrations.RunPython(backfill_registration_numbers, reverse_code=migrations.RunPython.noop),
        # Step 3: Make it non-nullable and unique
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
