# Generated by Django 6.0.4 on 2026-05-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Behac International Academy', max_length=200)),
                ('motto', models.CharField(blank=True, default='', max_length=500)),
                ('tagline', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('portal_name', models.CharField(blank=True, default='', help_text='Name shown on the login portal', max_length=200)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Information',
            },
        ),
    ]
