# Generated by Django 6.0.4 on 2026-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='primary_bg',
            field=models.CharField(default='#E8F5E9', help_text='Background tint color (e.g. #E8F5E9)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='primary_dark',
            field=models.CharField(default='#1B5E20', help_text='Dark primary color (e.g. #1B5E20)', max_length=7),
        ),
        migrations.AddField(
            model_name='schoolinfo',
            name='primary_light',
            field=models.CharField(default='#4CAF50', help_text='Light primary color (e.g. #4CAF50)', max_length=7),
        ),
    ]
