# Generated by Django 6.0.4 on 2026-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schoolinfo_primary_bg_schoolinfo_primary_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Default hero background image (used when no Hero Slides are set)', null=True, upload_to='hero/'),
        ),
    ]
