# Generated by Django 6.0.4 on 2026-05-07 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=100, verbose_name="Child's First Name")),
                ('child_middle_name', models.CharField(blank=True, max_length=100, verbose_name="Child's Middle Name")),
                ('child_last_name', models.CharField(max_length=100, verbose_name="Child's Last Name")),
                ('child_date_of_birth', models.DateField(verbose_name="Child's Date of Birth")),
                ('child_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name="Child's Gender")),
                ('child_birth_certificate', models.CharField(max_length=100, verbose_name='Birth Certificate Number')),
                ('child_previous_school', models.CharField(blank=True, max_length=200, verbose_name='Previous School (if any)')),
                ('grade_applying_for', models.CharField(max_length=50, verbose_name='Grade/Class Applying For')),
                ('parent_full_name', models.CharField(max_length=200, verbose_name='Parent/Guardian Full Name')),
                ('parent_relationship', models.CharField(max_length=50, verbose_name='Relationship to Child')),
                ('parent_mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('parent_occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('parent_nida', models.CharField(blank=True, max_length=20, verbose_name='NIDA Number (if any)')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('street', models.CharField(max_length=200, verbose_name='Street/Village')),
                ('additional_info', models.TextField(blank=True, verbose_name='Additional Information')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-published_at'],
            },
        ),
    ]
