# Generated by Django 6.0.4 on 2026-05-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grade_applying_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classlevel', verbose_name='Grade/Class Applying For'),
        ),
    ]
