# Generated by Django 6.0.4 on 2026-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_application_grade_applying_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Slide Image')),
                ('title', models.CharField(blank=True, help_text='Optional: Overrides the default hero title for this slide', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional: Overrides the default hero subtitle for this slide', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
