# Generated by Django 6.0.4 on 2026-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_paragraph_1', models.TextField(blank=True, default='', help_text='First about paragraph')),
                ('about_paragraph_2', models.TextField(blank=True, default='', help_text='Second about paragraph')),
                ('about_paragraph_3', models.TextField(blank=True, default='', help_text='Third about paragraph')),
                ('about_paragraph_4', models.TextField(blank=True, default='', help_text='Fourth about paragraph')),
                ('mission', models.TextField(blank=True, default='', help_text='School mission statement')),
                ('vision', models.TextField(blank=True, default='', help_text='School vision statement')),
                ('stat_pupils', models.CharField(default='500+', help_text='Pupils count display (e.g. 500+)', max_length=20)),
                ('stat_teachers', models.CharField(default='30+', help_text='Teachers count display (e.g. 30+)', max_length=20)),
                ('stat_years', models.CharField(default='10+', help_text='Years established display (e.g. 10+)', max_length=20)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Dar es Salaam, Tanzania', max_length=300)),
                ('phone_1', models.CharField(default='+255 712 345 678', max_length=30)),
                ('phone_2', models.CharField(blank=True, default='+255 712 345 679', max_length=30)),
                ('email_1', models.EmailField(default='info@behac.ac.tz', max_length=254)),
                ('email_2', models.EmailField(blank=True, default='admissions@behac.ac.tz', max_length=254)),
                ('office_hours', models.CharField(default='Monday - Friday: 7:30 AM - 4:00 PM', max_length=200)),
                ('saturday_hours', models.CharField(blank=True, default='Saturday: 8:00 AM - 12:00 PM', max_length=200)),
                ('whatsapp', models.CharField(blank=True, default='+255 712 345 678', max_length=30)),
                ('google_maps_url', models.URLField(blank=True, default='https://maps.google.com/?q=Dar+es+Salaam+Tanzania')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('whatsapp_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-star', help_text='Bootstrap icon class', max_length=50)),
                ('title', models.CharField(help_text='Value title', max_length=200)),
                ('description', models.TextField(help_text='Value description')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-star', help_text='Bootstrap icon class (e.g. bi-book, bi-people)', max_length=50)),
                ('title', models.CharField(help_text='Feature title', max_length=200)),
                ('description', models.TextField(help_text='Feature description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
    ]
