# Generated by Django 6.0.4 on 2026-05-01 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('hire_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qualification', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='staff/cv/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='staff/certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Admin', 'Administration'), ('Support', 'Support Services')], max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('hire_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qualification', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='staff/cv/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='staff/certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='academics.classlevel')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(help_text='First day of the month (e.g., 2025-01-01)')),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('content_type', 'object_id', 'month')},
            },
        ),
    ]
