# Generated by Django 6.0.4 on 2026-05-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
    ]
