# Generated by Django 6.0.4 on 2026-05-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_drop_unique_salary_payment'),
    ]

    operations = [
    ]
