# Generated by Django 6.0.4 on 2026-05-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_level', 'day_of_week', 'period', 'academic_year')},
        ),
    ]
