# Generated by Django 6.0.4 on 2026-05-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
        ('core', '0001_initial'),
        ('students', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='classlevel',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['term', 'name']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-exam__term', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['class_level', 'day_of_week', 'period']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.term'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.classlevel'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_level', 'day_of_week', 'period')},
        ),
    ]
