# Generated by Django 6.0.4 on 2026-05-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_assignment_options_alter_attendance_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_level', 'day_of_week', 'period', 'academic_year')},
        ),
    ]
